# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora_cita',
            field=models.TimeField(choices=[('11:15', '11:15'), ('11:45', '11:45'), ('12:15', '12:15'), ('12:30', '12:30')], default='11:30', verbose_name='Hora'),
        ),
    ]
