# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='id',
        ),
        migrations.AddField(
            model_name='cita',
            name='cita_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
