# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_creacion_cita',
            field=models.DateField(auto_now=True, verbose_name='Creacion'),
        ),
    ]
