# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='telefono_cliente',
            field=models.CharField(max_length=20),
        ),
    ]
