# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateTimeField(),
        ),
    ]
