# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='direccion',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='nombre_cliente',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='telefono_cliente',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
