# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_auto_20161127_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fecha_creacion_cita',
        ),
    ]
