# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_cita_hora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hora',
        ),
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
