# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_auto_20161128_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora_cita',
            field=models.TimeField(choices=[('11:15:00', '11:15:00'), ('11:40:00', '11:40:00'), ('12:15:00', '12:15:00'), ('12:30:00', '12:30:00')], default='11:15:00', verbose_name='Hora'),
        ),
    ]
