# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_cita_fecha_creacion_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora_cita',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_creacion_cita',
            field=models.DateTimeField(auto_now=True, verbose_name='Creacion'),
        ),
    ]
