# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_auto_20161109_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.CharField(max_length=5),
        ),
    ]
