# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_auto_20161128_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora_cita',
            field=models.TimeField(verbose_name='Hora'),
        ),
    ]
