# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0004_auto_20161109_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default=0, verbose_name='Hora de la cita'),
        ),
    ]
