# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0007_auto_20161109_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='hora',
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
