# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0009_auto_20161109_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
