# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0010_auto_20161109_0229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
