# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('ventas', '0002_auto_20161128_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaproducto',
            name='id_venta',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ventaservicio',
            name='id_venta',
        ),
        migrations.RemoveField(
            model_name='ventaservicio',
            name='servicio',
        ),
        migrations.AddField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VentaProducto',
        ),
        migrations.DeleteModel(
            name='VentaServicio',
        ),
    ]
