# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('ventas', '0004_auto_20161203_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='barbero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.Barbero'),
            preserve_default=False,
        ),
    ]
