# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_imagen', models.CharField(max_length=20)),
                ('descripcion_imagen', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('marca_producto', models.CharField(max_length=50)),
                ('precio_unitario_producto', models.IntegerField(default=0)),
                ('stock_producto', models.IntegerField(default=0)),
                ('descripcion_producto', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
    ]
