# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('marca_producto', models.CharField(max_length=50)),
                ('precio_unitario_producto', models.IntegerField(default=0)),
                ('stock_producto', models.IntegerField(default=0)),
            ],
        ),
    ]
