# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('marca_producto', models.CharField(max_length=50)),
                ('precio_unitario_producto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_producto', models.IntegerField(default=0)),
                ('descripcion_producto', models.TextField()),
                ('imagen_producto', models.FileField(upload_to=b'')),
            ],
        ),
    ]
