# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('concepto', models.CharField(max_length=10)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Barbero')),
            ],
        ),
    ]
