# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
