# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='titulo_imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
    ]
