# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.FileField(upload_to=b''),
        ),
    ]
