# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20161115_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='titulo_imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
