# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='id_producto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
