# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20161117_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario_producto',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
