# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20161207_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha_operacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='salida',
            name='fecha_operacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
