# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20161212_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_producto',
            field=models.PositiveIntegerField(),
        ),
    ]
