# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20161212_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
            preserve_default=False,
        ),
    ]
