# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_entrada_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='producto',
        ),
    ]
