# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tweet_act', models.CharField(max_length=30)),
                ('fb_act', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=350)),
            ],
        ),
    ]
