# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbero',
            old_name='fb_act',
            new_name='cuenta_facebook',
        ),
        migrations.RenameField(
            model_name='barbero',
            old_name='tweet_act',
            new_name='cuenta_twitter',
        ),
    ]
