# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio_servicio',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
