# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20161003_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbero',
            old_name='cuenta_facebook',
            new_name='cta_twitter_bar',
        ),
        migrations.RenameField(
            model_name='barbero',
            old_name='cuenta_twitter',
            new_name='cuenta_facebook_bar',
        ),
        migrations.RenameField(
            model_name='barbero',
            old_name='descripcion',
            new_name='descripcion_bar',
        ),
        migrations.RenameField(
            model_name='barbero',
            old_name='nombre',
            new_name='nombre_bar',
        ),
    ]
