# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20161003_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbero',
            old_name='cta_twitter_bar',
            new_name='cuenta_twitter_bar',
        ),
    ]
