# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20161003_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corte', models.CharField(max_length=30)),
                ('descripcion_corte', models.CharField(max_length=50)),
                ('imagen_corte', models.CharField(max_length=200)),
            ],
        ),
    ]
