# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_corte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbero',
            old_name='nombre_bar',
            new_name='nombre_barbero',
        ),
    ]
