# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20161003_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=30)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('imagen_corte', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Corte',
        ),
    ]
