# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20161016_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='direccion_cliente',
            field=models.CharField(default='Dr. Barragan No. 594', max_length=150),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(auto_now_add=True, blank=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='telefono_cliente',
            field=models.CharField(default='044(55)29229929', max_length=20),
        ),
    ]
