# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20161016_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(default='2020-09-90'),
        ),
    ]
