# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20161016_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('marca_producto', models.CharField(max_length=50)),
                ('precio_unitario_producto', models.IntegerField(default=0)),
                ('stock_producto', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='precio',
            new_name='precio_servicio',
        ),
        migrations.AddField(
            model_name='cita',
            name='confirmacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='nombre_servicio',
            field=models.CharField(default='Corte de pelo', max_length=60),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre_servicio',
            field=models.CharField(default='Corte de pelo', max_length=30),
        ),
    ]
