# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_remove_cita_fecha_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.FileField(upload_to=b'')),
            ],
        ),
    ]
