# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='titulo',
        ),
    ]
