# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_remove_imagen_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
