# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('marca_producto', models.CharField(max_length=50)),
                ('precio_unitario_producto', models.IntegerField(default=0)),
                ('stock_producto', models.IntegerField(default=0)),
                ('imagen_producto', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='barbero',
            name='descripcion_barbero',
            field=models.TextField(max_length=350),
        ),
    ]
