# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20161105_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagen',
            new_name='Galeria',
        ),
        migrations.AddField(
            model_name='barbero',
            name='fotografia_barbero',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
