# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20161105_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='titulo_imagen',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galeria',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
