# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20161109_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion_producto',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
