# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_producto_descripcion_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
