# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_delete_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion_producto',
            field=models.TextField(),
        ),
    ]
